routing:
  services:
    service1: http://service1:8081/
    service2: http://service2:8082/

  rules:
    - pattern: ".*/test1.*"
      serviceToForward: service1
    - pattern: ".*/test2.*"
      serviceToForward: service2